"""add gtm-skills-repo import fields to gtm_skills

Revision ID: 3140aa424e6a
Revises: edbb26d0822f
Create Date: 2026-08-21 21:10:45.454597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3140aa424e6a'
down_revision = 'edbb26d0822f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gtm_skills', sa.Column('content_body', sa.Text(), nullable=True))
    op.add_column('gtm_skills', sa.Column('source_id', sa.String(length=160), nullable=True))
    op.add_column('gtm_skills', sa.Column('source_url', sa.String(length=500), nullable=True))
    op.add_column('gtm_skills', sa.Column('difficulty', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_gtm_skills_source_id'), 'gtm_skills', ['source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gtm_skills_source_id'), table_name='gtm_skills')
    op.drop_column('gtm_skills', 'difficulty')
    op.drop_column('gtm_skills', 'source_url')
    op.drop_column('gtm_skills', 'source_id')
    op.drop_column('gtm_skills', 'content_body')
    # ### end Alembic commands ###
