"""gtm skills initial schema

Revision ID: edbb26d0822f
Revises: 
Create Date: 2026-08-21 16:42:00.819206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edbb26d0822f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtm_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtm_collections_slug'), 'gtm_collections', ['slug'], unique=True)
    op.create_table('gtm_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gtm_stages_position', 'gtm_stages', ['position'], unique=False)
    op.create_index(op.f('ix_gtm_stages_slug'), 'gtm_stages', ['slug'], unique=True)
    op.create_table('gtm_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtm_workflows_session_id'), 'gtm_workflows', ['session_id'], unique=False)
    op.create_table('gtm_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('when_to_use', sa.Text(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workflow_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_type', sa.String(length=16), server_default='native', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='live', nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['gtm_stages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gtm_skills_execution_type', 'gtm_skills', ['execution_type'], unique=False)
    op.create_index(op.f('ix_gtm_skills_slug'), 'gtm_skills', ['slug'], unique=True)
    op.create_index(op.f('ix_gtm_skills_stage_id'), 'gtm_skills', ['stage_id'], unique=False)
    op.create_index('ix_gtm_skills_stage_status', 'gtm_skills', ['stage_id', 'status'], unique=False)
    op.create_table('gtm_collection_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['gtm_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['gtm_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'skill_id', name='uq_collection_skill')
    )
    op.create_index(op.f('ix_gtm_collection_skills_collection_id'), 'gtm_collection_skills', ['collection_id'], unique=False)
    op.create_index(op.f('ix_gtm_collection_skills_skill_id'), 'gtm_collection_skills', ['skill_id'], unique=False)
    op.create_table('gtm_skill_bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['gtm_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'skill_id', name='uq_session_skill_bookmark')
    )
    op.create_index(op.f('ix_gtm_skill_bookmarks_session_id'), 'gtm_skill_bookmarks', ['session_id'], unique=False)
    op.create_index(op.f('ix_gtm_skill_bookmarks_skill_id'), 'gtm_skill_bookmarks', ['skill_id'], unique=False)
    op.create_table('gtm_skill_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('related_skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['related_skill_id'], ['gtm_skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['gtm_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'related_skill_id', name='uq_skill_relation')
    )
    op.create_index(op.f('ix_gtm_skill_relations_related_skill_id'), 'gtm_skill_relations', ['related_skill_id'], unique=False)
    op.create_index(op.f('ix_gtm_skill_relations_skill_id'), 'gtm_skill_relations', ['skill_id'], unique=False)
    op.create_table('gtm_skill_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['gtm_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtm_skill_runs_session_id'), 'gtm_skill_runs', ['session_id'], unique=False)
    op.create_index('ix_gtm_skill_runs_skill_created', 'gtm_skill_runs', ['skill_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_gtm_skill_runs_skill_id'), 'gtm_skill_runs', ['skill_id'], unique=False)
    op.create_table('gtm_workflow_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['gtm_skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['gtm_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'skill_id', name='uq_workflow_skill')
    )
    op.create_index(op.f('ix_gtm_workflow_items_skill_id'), 'gtm_workflow_items', ['skill_id'], unique=False)
    op.create_index(op.f('ix_gtm_workflow_items_workflow_id'), 'gtm_workflow_items', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gtm_workflow_items_workflow_id'), table_name='gtm_workflow_items')
    op.drop_index(op.f('ix_gtm_workflow_items_skill_id'), table_name='gtm_workflow_items')
    op.drop_table('gtm_workflow_items')
    op.drop_index(op.f('ix_gtm_skill_runs_skill_id'), table_name='gtm_skill_runs')
    op.drop_index('ix_gtm_skill_runs_skill_created', table_name='gtm_skill_runs')
    op.drop_index(op.f('ix_gtm_skill_runs_session_id'), table_name='gtm_skill_runs')
    op.drop_table('gtm_skill_runs')
    op.drop_index(op.f('ix_gtm_skill_relations_skill_id'), table_name='gtm_skill_relations')
    op.drop_index(op.f('ix_gtm_skill_relations_related_skill_id'), table_name='gtm_skill_relations')
    op.drop_table('gtm_skill_relations')
    op.drop_index(op.f('ix_gtm_skill_bookmarks_skill_id'), table_name='gtm_skill_bookmarks')
    op.drop_index(op.f('ix_gtm_skill_bookmarks_session_id'), table_name='gtm_skill_bookmarks')
    op.drop_table('gtm_skill_bookmarks')
    op.drop_index(op.f('ix_gtm_collection_skills_skill_id'), table_name='gtm_collection_skills')
    op.drop_index(op.f('ix_gtm_collection_skills_collection_id'), table_name='gtm_collection_skills')
    op.drop_table('gtm_collection_skills')
    op.drop_index('ix_gtm_skills_stage_status', table_name='gtm_skills')
    op.drop_index(op.f('ix_gtm_skills_stage_id'), table_name='gtm_skills')
    op.drop_index(op.f('ix_gtm_skills_slug'), table_name='gtm_skills')
    op.drop_index('ix_gtm_skills_execution_type', table_name='gtm_skills')
    op.drop_table('gtm_skills')
    op.drop_index(op.f('ix_gtm_workflows_session_id'), table_name='gtm_workflows')
    op.drop_table('gtm_workflows')
    op.drop_index(op.f('ix_gtm_stages_slug'), table_name='gtm_stages')
    op.drop_index('ix_gtm_stages_position', table_name='gtm_stages')
    op.drop_table('gtm_stages')
    op.drop_index(op.f('ix_gtm_collections_slug'), table_name='gtm_collections')
    op.drop_table('gtm_collections')
    # ### end Alembic commands ###
